### PR TITLE
Task 5: megumii

### PR DESCRIPTION
**Pull request by Megumiiiiii**

### CODE REVIEW

**Comment by IneryTestnet** [comment]
Please publish your solution online, and provide us with a link so we can test your web-app ourselves.

**Comment by Megumiiiiii** [comment]
I post it on README.md

https://inery-task-5.megumii.xyz/

**Comment by Megumiiiiii** [comment]
> Please publish your solution online, and provide us with a link so we can test your web-app ourselves.
I post it on README.md

https://inery-task-5.megumii.xyz/

**Comment by Megumiiiiii** [comment]
> Please publish your solution online, and provide us with a link so we can test your web-app ourselves.

Screenshot_8

**Pull request closed without merging**
