### PR TITLE
task4

### PR DESCRIPTION
**Pull request by ahmkah**
task4

### CODE REVIEW

**Comment by IneryTestnet** [comment]
Please, submit your solution again. Your solution must have directory with your account name only. Within that directory you should have README.md and a solution that is valid. Merge your solution on the task4 branch, not on the main.

**Comment by ahmkah** [comment]
ok, I edited my solution based on your comment.

**Comment by ahmkah** [comment]
ok

**Comment by ahmkah** [comment]
Merge my solution on the task4 branch

**Pull request closed without merging**
