### PR TITLE
Task 4 - awan

### PR DESCRIPTION
**Pull request by nodemual**

### CODE REVIEW

**Comment by IneryTestnet** [comment]
The overall code is good but you must commit to the task4 branch.

**Comment by nodemual** [comment]
https://github.com/inery-blockchain/inery-testnet-faucet-tasks/pull/708 

// please check

**Comment by 0xzur4** [comment]
> The overall code is good but you must commit to the task4 branch.

https://github.com/inery-blockchain/inery-testnet-faucet-tasks/pull/708

please check sir

**Comment by 0xzur4** [comment]
> The overall code is good but you must commit to the task4 branch.

why am i labeled duplicate?

**Pull request closed without merging**
